# aic-themes (Endspace) theme configuration

favicon: /favicon.ico
avatar: /images/avatar.svg
author: ''
bio: ''

menu:
  Home: /
  Category: /categories/
  Tag: /tags/
  Archive: /archives/
  Portfolio: /portfolio/
  Friends: /friends/
  Search: /search/

endspace:
  loading_cover: true
  loading_site_name: 柚木鉉の空間
  loading_text_init: INITIALIZING
  loading_text_loading: LOADING
  loading_text_complete: READY
  loading_text_sweeping: LAUNCHING
  loading_text_fadeout: WELCOME
  loading_image: /svg/cloud.svg

  banner_watermark_text: YUZUKITSURU_SPACE
  article_watermark_text: 柚木鉉

  menu_category: true
  menu_tag: true
  menu_archive: true
  menu_search: true

  post_list_cover: true
  post_list_preview: true
  post_list_style: page   # page | scroll

  article_layout_vertical: false
  article_adjacent: true

contact:
  email: ''
  github: ''
  twitter: ''
  weibo: ''
  bilibili: ''
  telegram: ''
  instagram: ''
  youtube: ''
  linkedin: ''
  wechat_public: ''
  zhishixingqiu: ''
  xiaohongshu: ''

footer:
  enable_rss: true
  bei_an: ''
  bei_an_link: ''
  since: ''
